# Generated by Django 5.1 on 2024-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('sname', models.CharField(max_length=150)),
                ('tags', models.TextField()),
                ('sdesc', models.TextField()),
                ('ldesc', models.TextField()),
                ('img', models.FileField(upload_to='pic/%y/')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
