# Generated by Django 5.1 on 2024-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_member_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='country',
        ),
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.FileField(default='Unknown', upload_to='pic/%y/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(),
        ),
    ]
