# Generated by Django 5.1 on 2024-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_notes_country_notes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.FileField(upload_to='pic/%y/'),
        ),
    ]
