# Generated by Django 5.1 on 2024-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='plant_images/'),
        ),
    ]
