# Generated by Django 5.1 on 2024-10-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_notes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
    ]
