# Generated by Django 5.1 on 2024-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pic/%y/'),
        ),
    ]
